### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by Naelitz** [Naelitz/Herbies_DnD#3]
Want to make objects for every character that stores all their info and want to keep all the characters in a seperate folder but dont know how to access them at that point. 

Sprites.Java must be able to access the Skeleton.java in the sprites folder.

**Comment by nlowe** [comment]
Try organizing into packages (I've only added one below, but you get the gist):

```
src
└── sample
    ├── characters
    │   ├── Dragon.java
    │   └── Skeleton.java
    ├── Controller.java
    ├── DungeonMaster.java
    ├── Main.java
    ├── MapTile.java
    ├── Play.java
    ├── sample.fxml
    ├── Sprite.java
    ├── Sprites.java
    ├── TitleScreen.java
    └── Tools.java
```

And then in `Sprites.java`:

``` java
import sample.characters.Skeleton
```

IntelliJ should offer to refactor for you if you move them within the editor.

I would also recommend creating a `Character` superclass for common methods and properties shared across all characters, such as health and position. Then you can extend that class to make other classes:

``` java
class Skeleton extends Character{
    // Class Definition Here
}
```

**Comment by Naelitz** [comment]
I actually started that. Thanks I didnt know I had to import to get other folders to work.
